home: http://lauri.rooden.ee
name: Lauri's page
author: Lauri Rooden
email: lauri@rooden.ee
paginate: 25
permalink: /:year/:month/:day/:title.html
exclude:
- README
- post.sh
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
